In [1]:
 #Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
 import numpy as np

In [2]:

np.random.randint(1,100)

87

In [3]:
arr1 = np.array(np.random.randint(1,100, (3,3)))

In [4]:
arr1

array([[32, 34, 17],
       [15, 80, 72],
       [22, 29, 34]])

In [5]:
#to change its rows and coloumns.
arr2 =arr1.T

In [6]:
arr2

array([[32, 15, 22],
       [34, 80, 29],
       [17, 72, 34]])

In [8]:
#Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
l= [1,2,3,4,5,6,7,8,9,10]

In [9]:
arr = np.array(l)

In [10]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr1= arr.reshape(2,5)

In [12]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
arr2 = arr.reshape(5,2)

In [14]:
arr2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [29]:
#Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array
arr =np.random.rand(4,4)

In [34]:
print(arr)

[[0.44184183 0.08130053 0.32999219 0.93764604]
 [0.1040402  0.00136681 0.52268241 0.59160363]
 [0.20367933 0.87446178 0.68201786 0.73030412]
 [0.50255144 0.14887049 0.80791773 0.33899467]]


In [31]:
#to add a border of zeros around it
bordered_arr = np.pad(arr, pad_width=1, mode="constant")


In [33]:
print(bordered_arr)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.44184183 0.08130053 0.32999219 0.93764604 0.        ]
 [0.         0.1040402  0.00136681 0.52268241 0.59160363 0.        ]
 [0.         0.20367933 0.87446178 0.68201786 0.73030412 0.        ]
 [0.         0.50255144 0.14887049 0.80791773 0.33899467 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [38]:
 #Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
 arr = np.arange(10,61,5)

In [39]:
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


In [41]:
 #Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
#(uppercase, lowercase, title case, etc.) to each element.
arr = np.array(["python","numpy","pandas"])

In [42]:
arr

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [43]:
np.char.upper(arr)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [44]:
np.char.lower(arr)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [45]:
np.char.title(arr)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [52]:
#Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
words =np.array(["pwskills","data analytics"])

In [53]:
words

array(['pwskills', 'data analytics'], dtype='<U14')

In [55]:
spaced_words = np.array(["".join([char, " "]) for word in words for char in word])


print(spaced_words)



['p ' 'w ' 's ' 'k ' 'i ' 'l ' 'l ' 's ' 'd ' 'a ' 't ' 'a ' '  ' 'a '
 'n ' 'a ' 'l ' 'y ' 't ' 'i ' 'c ' 's ']


In [63]:
#Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

arr1 =np.array([[1,2,3,4],[5,6,7,8]])
arr2 =np.array([[9,10,11,12],[13,14,15,16]])

In [64]:
addition = arr1+arr2

In [65]:
addition

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [66]:
subtraction = arr1-arr2

In [67]:
subtraction

array([[-8, -8, -8, -8],
       [-8, -8, -8, -8]])

In [68]:
multiply = arr1*arr2

In [69]:
multiply

array([[  9,  20,  33,  48],
       [ 65,  84, 105, 128]])

In [70]:
division = arr1/arr2

In [71]:
division

array([[0.11111111, 0.2       , 0.27272727, 0.33333333],
       [0.38461538, 0.42857143, 0.46666667, 0.5       ]])

In [72]:
 #Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
 identity_mat= np.eye(5)

In [73]:
identity_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
diagonal_element = np.diag(identity_mat)

In [75]:
diagonal_element

array([1., 1., 1., 1., 1.])

In [76]:
 #Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
# this array
arr = np.random.randint(0,1000,100)

In [77]:
arr

array([177, 432, 652, 945, 639, 100, 984, 568,  69, 537, 949, 628, 149,
        74, 119, 134, 976, 831, 408, 681, 594, 705, 119, 334, 678, 760,
       128, 935, 320, 509,  44, 489, 851, 971, 300,  94, 117, 885,  51,
        78, 684, 132, 818, 739, 935, 779,  66, 789, 694, 798, 481, 139,
       404, 558,   1, 386, 857, 254, 750,  62, 640, 451, 743, 234, 983,
       784, 797, 538, 453, 136,  77, 102,  61, 337,  63, 709, 821, 439,
       602, 825, 792,  54, 565, 155, 543, 645,  14, 549, 795,  63, 901,
       468, 269, 949, 366, 797,  84, 199, 187, 217])

In [84]:
prime_num = np.fromfunction(filter(lambda i: i%2==0,arr))

TypeError: fromfunction() missing 1 required positional argument: 'shape'

In [85]:
 #Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
# averages.
daily_temperatures = np.random.randint(20, 30, size=30)
print(daily_temperatures)




[21 21 26 26 23 23 29 25 26 29 20 29 21 29 21 27 28 20 21 20 22 21 28 27
 24 24 25 20 29 29]


In [86]:
# Calculate weekly averages
weekly_averages = [daily_temperatures[i:i+7].mean() for i in range(0, len(daily_temperatures), 7)]
print(weekly_averages)


[24.142857142857142, 25.571428571428573, 22.714285714285715, 24.142857142857142, 29.0]
